// Encrypted-cookie session. The session payload is a JWE (A256GCM
// content-encrypted with a SHA-256-derived key from SESSION_SECRET)
// that lives in the `eex.session` HttpOnly cookie. Stateless — no
// server-side store. Rotating SESSION_SECRET invalidates every existing
// session, which is the right behavior for a forced sign-out.
//
// Why JWE instead of plain SignJWT: the payload includes the user's
// Plex auth token (so admin routes can call plex.tv on their behalf).
// SignJWT only signs — the payload is base64-readable, so a copied or
// logged cookie would expose the Plex token to anyone holding it.
// JWE encrypts the payload end-to-end so the cookie is opaque even if
// captured.

import { EncryptJWT, jwtDecrypt } from 'jose'
import { createHash } from 'node:crypto'
import type { Context } from 'hono'
import { getCookie, setCookie, deleteCookie } from 'hono/cookie'
import { env } from './env.js'

const COOKIE_NAME = 'eex.session'
const SESSION_TTL_DAYS = 30

export type Role = 'admin' | 'user'

/** Auth provider recorded in a device token at mint time (§3.2).
 *  'both' was eliminated — server-side config (which providers are
 *  enabled) lives in /api/version, not in the token. Clients branch on
 *  the presence of each mode independently.
 *  'apple' is added now (zero cost) so D17 changes are not reopened
 *  when Sign in with Apple lands in M2. */
export type AuthMode = 'plex' | 'local' | 'apple'

export type Session = {
  sub: string // plex user id (string for jwt sub claim)
  username: string
  role: Role
  /** Auth provider used when this session was created. Embedded in the
   *  session cookie so the device-token mint endpoint (D13) can read it
   *  server-side without inferring from plexAuthToken presence (fragile).
   *  Optional for backward-compat: cookies issued before D17 won't have
   *  this field; verifySession defaults missing values to 'plex' (all M1
   *  sessions are Plex-authenticated). Drop the default after one full
   *  cookie TTL (30 days post-D17 deploy). */
  auth_mode?: AuthMode
  /** The user's Plex auth token, threaded through so admin-only routes
   *  (e.g. /api/users) can call plex.tv on their behalf without us
   *  storing a long-lived owner token in env. Optional for forward-
   *  compatibility with existing sessions issued before this field
   *  existed — those users will need to re-auth before token-using
   *  endpoints work for them. */
  plexAuthToken?: string
  verifiedPlexServerId?: string
}

/** Derive the device-token `auth_mode` claim (§3.2) from the session
 *  that triggers a device-token mint.
 *
 *  Once D7 lands and all `sub` values carry a namespace prefix, the
 *  prefix alone is canonical (`plex:` → 'plex', `local:` → 'local',
 *  `apple:` → 'apple'). Until then (M1 sessions carry bare Plex IDs),
 *  `local:` and `apple:` are the only prefixes that can appear, so any
 *  un-prefixed sub is safely treated as Plex — which is correct for all
 *  M1 sessions.
 *
 *  auth_mode is NOT read from the session payload here (session.auth_mode
 *  would also be correct post-D17) — we derive from sub so this helper
 *  works even for session objects without the auth_mode field, e.g.,
 *  during the 30-day backward-compat window.
 */
export function authModeFromSession(session: Pick<Session, 'sub'>): AuthMode {
  if (session.sub.startsWith('local:')) return 'local'
  if (session.sub.startsWith('apple:')) return 'apple'
  return 'plex'
}

/** Type-guard: true when a mint request should carry auth_mode 'plex'.
 *  Convenience wrapper over authModeFromSession for callers that only
 *  need the boolean. */
export function isPlexSession(session: Pick<Session, 'sub'>): boolean {
  return authModeFromSession(session) === 'plex'
}

/** Input to mintDeviceToken. The caller (device-mint endpoint, D13)
 *  reads the validated session and the client-supplied pairing body,
 *  then passes this to mint the JWE bearer token.
 *
 *  auth_mode is NOT supplied by the caller directly — it is DERIVED from
 *  the session via authModeFromSession. This type captures the shape
 *  D13's endpoint will build before calling mintDeviceToken. */
export type DeviceTokenInput = {
  /** Namespace-prefixed subject (§8). Must already be prefixed
   *  (e.g. 'plex:12345'). Pre-D7 callers pass the bare Plex id; D7
   *  will update this once sub prefixes are deployed universally. */
  sub: string
  role: Role
  /** auth_mode derived from the triggering session via authModeFromSession.
   *  The mint endpoint MUST call authModeFromSession(session) and pass
   *  the result here — it MUST NOT let the client supply this value. */
  auth_mode: AuthMode
  /** Stable ULID generated by the client and sent in the pairing body.
   *  Stored in Keychain on-device. */
  device_id: string
  /** Advisory platform string ('tvos' | 'ios' | 'ipados' | 'macos').
   *  Validators warn on unknown values but MUST NOT reject. */
  device_platform: string
  /** Stable server UUID from server_state (§12.3). */
  server_id: string
}

/** Mint a device-token JWE (§3.2).
 *
 *  STUB — full body is D13's responsibility (requires D2a for
 *  DEVICE_TOKEN_SECRET and D5 for server.db where device_tokens rows
 *  are inserted). This signature is locked here by D17 so D13 has a
 *  typed target to implement and the device-mint endpoint can import
 *  and call it without a signature change.
 *
 *  When D13 implements the body:
 *  - Derive the A256GCM key via HKDF (see §3.3 / D18)
 *  - Set aud: 'device', iss: 'eex', jti: <new ULID>
 *  - Set nbf == iat, exp == iat + 180 days
 *  - Insert a row into device_tokens (§3.4)
 *
 *  @throws once D13 lands if DEVICE_TOKEN_SECRET is absent from env.
 */
export async function mintDeviceToken(_input: DeviceTokenInput): Promise<string> {
  // TODO(D13): implement JWE mint. The signature and DeviceTokenInput
  // shape are locked; wire the body once D2a (DEVICE_TOKEN_SECRET) and
  // D5 (server.db) are merged.
  throw new Error(
    'mintDeviceToken: not yet implemented. Implement in D13 (requires D2a + D5).',
  )
}

// A256GCM requires a 32-byte key. SESSION_SECRET is arbitrary-length
// user input, so derive a fixed-size key with SHA-256.
const key = createHash('sha256').update(env.sessionSecret, 'utf8').digest()

export async function createSession(payload: Session): Promise<string> {
  return await new EncryptJWT({ ...payload })
    .setProtectedHeader({ alg: 'dir', enc: 'A256GCM' })
    .setIssuedAt()
    .setExpirationTime(`${SESSION_TTL_DAYS}d`)
    .encrypt(key)
}

export async function verifySession(token: string): Promise<Session | null> {
  try {
    const { payload } = await jwtDecrypt(token, key)
    if (typeof payload.sub !== 'string') return null
    if (typeof payload.username !== 'string') return null
    const role = payload.role
    if (role !== 'admin' && role !== 'user') return null
    const plexAuthToken =
      typeof payload.plexAuthToken === 'string' ? payload.plexAuthToken : undefined
    const verifiedPlexServerId =
      typeof payload.verifiedPlexServerId === 'string' ? payload.verifiedPlexServerId : undefined
    // Backward-compat default: cookies issued before D17 have no auth_mode
    // field. All M1 sessions are Plex-authenticated, so 'plex' is the safe
    // fallback. TODO: drop this default after 2026-06-25 (30 days post-D17
    // deploy) — at that point all active cookies will carry an explicit value.
    const rawAuthMode = payload.auth_mode
    const auth_mode: AuthMode =
      rawAuthMode === 'plex' || rawAuthMode === 'local' || rawAuthMode === 'apple'
        ? rawAuthMode
        : 'plex'
    return {
      sub: payload.sub,
      username: payload.username,
      role,
      auth_mode,
      ...(plexAuthToken ? { plexAuthToken } : {}),
      ...(verifiedPlexServerId ? { verifiedPlexServerId } : {}),
    }
  } catch {
    return null
  }
}

export async function setSessionCookie(c: Context, session: Session): Promise<void> {
  const token = await createSession(session)
  setCookie(c, COOKIE_NAME, token, {
    httpOnly: true,
    secure: env.isProd,
    sameSite: env.isProd ? 'None' : 'Lax',
    path: '/',
    maxAge: SESSION_TTL_DAYS * 24 * 60 * 60,
  })
}

export function clearSessionCookie(c: Context): void {
  deleteCookie(c, COOKIE_NAME, { path: '/' })
}

export async function readSession(c: Context): Promise<Session | null> {
  const token = getCookie(c, COOKIE_NAME)
  if (!token) return null
  return await verifySession(token)
}
